### ISSUE TITLE
Thymio Web Bridge Refuses to Work

### ISSUE THREAD

**Issue by sharon13m** [aseba-community/thymio-scratchx#11]
I have a mac, and the web bridge will work, and connect to thymio and such.  I may unplug the Thymio at some point and then attempt to reconnect to the web bridge, and try also restarting Thymio, but the web bridge will not open, no matter how many times I Force quit and restart Thymio.  I tried with cord and with wireless.  I think the only work around is restarting the Mac computer- which makes me think some kind of code continues to run even after force quitting, preventing the program from reopening and establishing a connection with Thymio.  The program just bounces around the the doc attempting to open.

**Comment by mbonani** [comment]
To have more information next time, please when its a happen launch the web bridge using right click->"show package content"->Contents->MacOS->thymiohttp

Also this bug is more related to aseba and should be in aseba repo.

**Comment by sharon13m** [comment]
It occured again, I did as you said, here is some of what showed up (it just repeats like this)..  And sometimes it does connect, many minutes later.  

x7fcd72500ce0)
incomingUserMsg msg (24,0x7fcd738002f0)
incomingUserMsg msg (24,0x7fcd72500ce0)
incomingUserMsg msg (24,0x7fcd72500ce0)
incomingUserMsg msg (24,0x7fcd726066f0)
incomingUserMsg msg (24,0x7fcd724047e0)
incomingUserMsg msg (24,0x7fcd726066f0)
incomingUserMsg msg (24,0x7fcd726066f0)
incomingUserMsg msg (24,0x7fcd726066f0)
0x7fcd74801038 Incoming connection from tcp:host=127.0.0.1;port=49883;connectionPort=3000
incoming for HTTP stream 0x7fcd74801038
0x7fcd74801038 Request GET /crossdomain.xml [ crossdomain.xml ] HTTP/1.1 new req 0x7fcd739000f0
0x7fcd739000f0 finishResponse 404 <>
0x7fcd74801038 sendAvailableResponses 1 in queue 0x7fcd739000f0
0x7fcd74801038 available responses sent, now 0 in queue
0x7fcd74801038 sendAvailableResponses 0 in queue
0x7fcd74801038 available responses sent, now 0 in queue
HttpInterface::run 1 streams to shut down 0x7fcd74801038
0x7fcd74801038 shutting down stream
0x7fcd74801038 Connection closed to tcp:host=127.0.0.1;port=49883;connectionPort=3000
0x7fcd74801038 Connection closed, removed 0 pending shutdowns
incomingUserMsg msg (24,0x7fcd738002f0)
incomingUserMsg msg (24,0x7fcd72500c80)
incomingUserMsg msg (24,0x7fcd72500c80)
incomingUserMsg msg (24,0x7fcd726066f0)
incomingUserMsg msg (24,0x7fcd72500c80)
incomingUserMsg msg (24,0x7fcd72500c80)
incomingUserMsg msg (24,0x7fcd72500c80)
incomingUserMsg msg (24,0x7fcd738002f0)
incomingUserMsg msg (24,0x7fcd726066f0)
incomingUserMsg msg (24,0x7fcd738002f0)
incomingUserMsg msg (24,0x7fcd72500c80)








incomingUserMsg msg (24,0x7fcd72404760)
incomingUserMsg msg (24,0x7fcd724047e0)
incomingUserMsg msg (24,0x7fcd72500ce0)
incomingUserMsg msg (24,0x7fcd73800150)
incomingUserMsg msg (24,0x7fcd73800150)
incomingUserMsg msg (24,0x7fcd726066f0)
incomingUserMsg msg (24,0x7fcd72404760)
0x7fcd74801038 Incoming connection from tcp:host=127.0.0.1;port=49895;connectionPort=3000
incoming for HTTP stream 0x7fcd74801038
0x7fcd74801038 Request GET /crossdomain.xml [ crossdomain.xml ] HTTP/1.1 new req 0x7fcd72501420
0x7fcd72501420 finishResponse 404 <>
0x7fcd74801038 sendAvailableResponses 1 in queue 0x7fcd72501420
0x7fcd74801038 available responses sent, now 0 in queue
0x7fcd74801038 sendAvailableResponses 0 in queue
0x7fcd74801038 available responses sent, now 0 in queue
HttpInterface::run 1 streams to shut down 0x7fcd74801038
0x7fcd74801038 shutting down stream
0x7fcd74801038 Connection closed to tcp:host=127.0.0.1;port=49895;connectionPort=3000
0x7fcd74801038 Connection closed, removed 0 pending shutdowns
incomingUserMsg msg (24,0x7fcd725010a0)
incomingUserMsg msg (24,0x7fcd72404760)
incomingUserMsg msg (24,0x7fcd724047e0)
incomingUserMsg msg (24,0x7fcd72500ce0)
incomingUserMsg msg (24,0x7fcd72404760)
incomingUserMsg msg (24,0x7fcd72500ce0)
incomingUserMsg msg (24,0x7fcd72500ce0)
incomingUserMsg msg (24,0x7fcd724047e0)
incomingUserMsg msg (24,0x7fcd738002f0)
incomingUserMsg msg (24,0x7fcd72500ce0)
incomingUserMsg msg (24,0x7fcd72500ce0)
incomingUserMsg msg (24,0x7fcd726066f0)
incomingUserMsg msg (24,0x7fcd738002f0)
incomingUserMsg msg (24,0x7fcd726066f0)

**Comment by mbonani** [comment]
close issue here, it is open in aseba https://github.com/aseba-community/aseba/issues/718
